# Generated by Django 5.0.1 on 2024-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='skill',
            field=models.TextField(max_length=100),
        ),
    ]
