# Generated by Django 5.0.1 on 2024-03-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0007_team_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id_user',
        ),
    ]
