# Generated by Django 5.0.1 on 2024-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0009_team_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='skill',
            field=models.TextField(blank=True),
        ),
    ]
