# Generated by Django 5.0.1 on 2024-03-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0010_alter_team_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
