# Generated by Django 5.0.1 on 2024-03-08 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('title', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('author_img', models.ImageField(upload_to='author_images')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('post_image', models.ImageField(upload_to='post_images')),
            ],
        ),
    ]
