# Generated by Django 5.0.1 on 2024-03-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0013_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('post_content', models.TextField()),
                ('author_twitter', models.TextField(blank=True)),
                ('author_linkedin', models.TextField(blank=True)),
                ('author_instagram', models.TextField(blank=True)),
                ('author_bio', models.TextField(blank=True)),
            ],
        ),
    ]
