# Generated by Django 5.0.1 on 2024-03-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0014_blogdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDetails',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_instagram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_twitter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
