# Generated by Django 5.0.1 on 2024-03-12 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0015_delete_blogdetails_blogpost_author_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('comment', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('website', models.TextField(blank=True)),
            ],
        ),
    ]
