# Generated by Django 5.0.1 on 2024-03-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0018_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
