# Generated by Django 5.0.1 on 2024-03-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0019_remove_team_id_alter_blogpost_id_alter_faq_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
    ]
