# Generated by Django 5.0.1 on 2024-03-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motif1', '0020_remove_comment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
